spring:
  config:
    activate:
      on-profile: local

jwt:
  secret: a2FrYW9jbG91ZHNjaG9vbGxvY2Fsa2FrYW9jbG91ZGMK
  access-token-expired-time: 3600
  refresh-token-expired-time: 2592000

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  secret: ${DEV_JWT_SECRET}
  access-token-expired-time: ${DEV_JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refresh-token-expired-time: ${DEV_JWT_REFRESH_TOKEN_EXPIRED_TIME}
