spring:
  application:
    name: niceteam-backend
  profiles:
    active: local
    group:
      local: db, jwt, mail
      dev: db, jwt, mail
aws:
  paramstore:
    name: niceteam
    enabled: true
    prefix: /config
    profile-separator: _

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace