spring:
  config:
    activate:
      on-profile: local

jwt:
  secret: a2FrYW9jbG91ZHNjaG9vbGxvY2Fsa2FrYW9jbG91ZGMK
  access-token-validity: 3600
  refresh-token-validity: 2592000

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  secret: ${jwt.secret}
  access-token-validity: ${jwt.refresh_token_validity}
  refresh-token-validity: ${jwt.refresh_token_validity}
