name: niceteam dev CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Make directory for deploy
        run: mkdir deploy

      - name: Copy jar
        run: cp ./build/libs/*.jar ./deploy
#
      - name: Copy appspec.yml
        run: cp ./appspec.yml ./deploy

      - name: Copy scripts
        run: cp ./scripts/* ./deploy

      - name: Make zip file
        run: zip -r -qq -j ./niceteam.zip ./deploy

      - name: Deliver to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./niceteam.zip s3://${{ secrets.AWS_DEPLOY_BUCKET }}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODEDEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_GROUP_DEV }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_DEPLOY_BUCKET }},bundleType=zip,key=niceteam.zip \
          --region ap-northeast-2